apiVersion: v1
kind: Service
metadata:
  name: accounts
spec:
  selector:
    app: accounts
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081  # You can change this, but keep it above 30000
