apiVersion: v1
kind: Service
metadata:
  name: cards
spec:
  selector:
    app: cards
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30083  # Custom node port, consistent with the pattern
