apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s

    scrape_configs:
      - job_name: 'accounts-service'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['accounts:8081']

      - job_name: 'transactions-service'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['transactions:8082']

      - job_name: 'cards-service'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['cards:8083']
